config/routes.rb
Rails.application.routes.draw do
  resources :candies
  resources :shelves
  resources :shops
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candy.rb
class Candy < ApplicationRecord
    belongs_to :shop
    belongs_to :shelf
end

app/models/shelf.rb
class Shelf < ApplicationRecord
    has_many :candies
    belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_many :shelves
    has_many :candies, through: :shelves

    # def total_shelves
    # shelves.joins(:shelves).uniq.count
    # end
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candies_controller.rb
class CandiesController < ApplicationController
  before_action :set_candy, only: [:show, :edit, :update, :destroy]

  # GET /candies
  # GET /candies.json
  def index
    @candies = Candy.all
  end

  # GET /candies/1
  # GET /candies/1.json
  def show
  end

  # GET /candies/new
  def new
    @candy = Candy.new
  end

  # GET /candies/1/edit
  def edit
  end

  # POST /candies
  # POST /candies.json
  def create
    @candy = Candy.new(candy_params)

    respond_to do |format|
      if @candy.save
        format.html { redirect_to @candy, notice: 'Candy was successfully created.' }
        format.json { render :show, status: :created, location: @candy }
      else
        format.html { render :new }
        format.json { render json: @candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candies/1
  # PATCH/PUT /candies/1.json
  def update
    respond_to do |format|
      if @candy.update(candy_params)
        format.html { redirect_to @candy, notice: 'Candy was successfully updated.' }
        format.json { render :show, status: :ok, location: @candy }
      else
        format.html { render :edit }
        format.json { render json: @candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candies/1
  # DELETE /candies/1.json
  def destroy
    @candy.destroy
    respond_to do |format|
      format.html { redirect_to candies_url, notice: 'Candy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candy
      @candy = Candy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def candy_params
      params.require(:candy).permit(:name, :shelved)
    end
end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController
  before_action :set_shelf, only: [:show, :edit, :update, :destroy]

  # GET /shelves
  # GET /shelves.json
  def index
    @shelves = Shelf.all
  end

  # GET /shelves/1
  # GET /shelves/1.json
  def show
  end

  # GET /shelves/new
  def new
    @shelf = Shelf.new
  end

  # GET /shelves/1/edit
  def edit
  end

  # POST /shelves
  # POST /shelves.json
  def create
    @shelf = Shelf.new(shelf_params)

    respond_to do |format|
      if @shelf.save
        format.html { redirect_to @shelf, notice: 'Shelf was successfully created.' }
        format.json { render :show, status: :created, location: @shelf }
      else
        format.html { render :new }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shelves/1
  # PATCH/PUT /shelves/1.json
  def update
    respond_to do |format|
      if @shelf.update(shelf_params)
        format.html { redirect_to @shelf, notice: 'Shelf was successfully updated.' }
        format.json { render :show, status: :ok, location: @shelf }
      else
        format.html { render :edit }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shelves/1
  # DELETE /shelves/1.json
  def destroy
    @shelf.destroy
    respond_to do |format|
      format.html { redirect_to shelves_url, notice: 'Shelf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shelf
      @shelf = Shelf.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shelf_params
      params.require(:shelf).permit(:candies, :shop_id)
    end
end

app/controllers/shops_controller.rb
require(byebug)
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    # @shops = Shop.joins(:candies)
    # @shops = SELECT COUNT(*) FROM "shops" INNER JOIN "candies" ON "shops"."id" = "variant_skus"."product_id" WHERE "product"."store_id" = ?):
    @shops = Shop.joins(:candies)
    # render json: @shops
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json 
  def create
    @shop = Shop.create(shop_params)
    render json: shop
  end

  # def create
  #   @shop = Shop.new(shop_params)

  #   respond_to do |format|
  #     if @shop.save
  #       format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
  #       format.json { render :show, status: :created, location: @shop }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @shop.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end


  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name, :shelves)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candies_helper.rb
module CandiesHelper
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/candies/_form.html.erb
<%= form_with(model: candy) do |form| %>
  <% if candy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candy.errors.count, "error") %> prohibited this candy from being saved:</h2>

      <ul>
        <% candy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :shelved %>
    <%= form.check_box :shelved %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/candies/edit.html.erb
<h1>Editing Candy</h1>

<%= render 'form', candy: @candy %>

<%= link_to 'Show', @candy %> |
<%= link_to 'Back', candies_path %>

app/views/candies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Shelved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candies.each do |candy| %>
      <tr>
        <td><%= candy.name %></td>
        <td><%= candy.shelved %></td>
        <td><%= link_to 'Show', candy %></td>
        <td><%= link_to 'Edit', edit_candy_path(candy) %></td>
        <td><%= link_to 'Destroy', candy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candy', new_candy_path %>

app/views/candies/new.html.erb
<h1>New Candy</h1>

<%= render 'form', candy: @candy %>

<%= link_to 'Back', candies_path %>

app/views/candies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @candy.name %>
</p>

<p>
  <strong>Shelved:</strong>
  <%= @candy.shelved %>
</p>

<%= link_to 'Edit', edit_candy_path(@candy) %> |
<%= link_to 'Back', candies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsReactTutorial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shelves/_form.html.erb
<%= form_with(model: shelf) do |form| %>
  <% if shelf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shelf.errors.count, "error") %> prohibited this shelf from being saved:</h2>

      <ul>
        <% shelf.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :candies %>
    <%= form.number_field :candies %>
  </div>

  <div class="field">
    <%= form.label :shop_id %>
    <%= form.text_field :shop_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shelves/edit.html.erb
<h1>Editing Shelf</h1>

<%= render 'form', shelf: @shelf %>

<%= link_to 'Show', @shelf %> |
<%= link_to 'Back', shelves_path %>

app/views/shelves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shelves</h1>

<table>
  <thead>
    <tr>
      <th>Candies</th>
      <th>Shop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shelves.each do |shelf| %>
      <tr>
        <td><%= shelf.candies %></td>
        <td><%= shelf.shop_id %></td>
        <td><%= link_to 'Show', shelf %></td>
        <td><%= link_to 'Edit', edit_shelf_path(shelf) %></td>
        <td><%= link_to 'Destroy', shelf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shelf', new_shelf_path %>

app/views/shelves/new.html.erb
<h1>New Shelf</h1>

<%= render 'form', shelf: @shelf %>

<%= link_to 'Back', shelves_path %>

app/views/shelves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Candies:</strong>
  <%= @shelf.candies %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @shelf.shop_id %>
</p>

<%= link_to 'Edit', edit_shelf_path(@shelf) %> |
<%= link_to 'Back', shelves_path %>

app/views/shops/_form.html.erb
<%= form_with(model: shop) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :shelves %>
    <%= form.number_field :shelves %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops List</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Shelves</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.shelves %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>    
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Shelves:</strong>
  <%= @shop.shelves %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>